return {
	PICKUP_RADIUS = 8,
	EQUALIZER_HEALTH_DIFF = 20,--how big the HP gap should be to activate equalizer
	EQUALIZER_MAX_HEALTH = 30,--how little health a player should have for equalizer

	FORGE_MELEE_HEALTH = 150,
	FORGE_MELEE_DAMAGE = 50,
	FORGE_MELEE_HAMMER_DAMAGE = 100,
	FORGE_MELEE_SPEAR_DAMAGE = 200,
	FORGE_MELEE_PIKE_DAMAGE = 150,

	FORGE_MAGE_HEALTH = 100,
	FORGE_MAGE_DAMAGE = 50,
	FORGE_MAGE_BOOK_DAMAGE = 65,
	FORGE_MAGE_METEOR_DAMAGE = 300,
	FORGE_MAGE_SUMMON_DAMAGE = 30,
	FORGE_MAGE_SUMMON_HEALTH = 150,
	FORGE_MAGE_HEALBLOOMS_DEFENSE = 0.75,
	
	SKILLTREE_COOLDOWN_1 = 0.10,
	SKILLTREE_COOLDOWN_2 = 0.25,
	SKILLTREE_DAMAGE_1 = 1.10,
	SKILLTREE_DAMAGE_2 = 1.25 / 1.10,
	SKILLTREE_DAMAGE_BUFF_AMOUNT = 0.1,
	SKILLTREE_DAMAGE_BUFF_STACKS = 5,
	SKILLTREE_DAMAGE_BUFF_DURATION = 5,
	SKILLTREE_FIREBOMB_PASSIVE_COOLDOWN = 0.5,
	SKILLTREE_FIREBOMB_FIRECIRCLE_DAMAGE_PER_LEVEL = 1,
	SKILLTREE_FIREBOMB_FIRECIRCLE_DURATION = 10,
	
}