return {
	DEFAULT_DAMAGE = 50,
	
	SKILLTREE_COOLDOWN_1 = 0.10,
	SKILLTREE_COOLDOWN_2 = 0.25,
	SKILLTREE_DAMAGE_1 = 1.10,
	SKILLTREE_DAMAGE_2 = 1.25 /1.10,
	SKILLTREE_DAMAGE_BUFF_AMOUNT = 0.1,
	SKILLTREE_DAMAGE_BUFF_STACKS = 5,
	SKILLTREE_DAMAGE_BUFF_DURATION = 5,
	SKILLTREE_FIREBOMB_FIRECIRCLE_DAMAGE_PER_LEVEL = 1,
	
}